### ISSUE TITLE
HP - bloc planète - différences hover

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#103]
Comme discuté hier soir en réunion, voici les différences que j'ai entre mode connecté ou non et hover ou nom sur l'image de l'utilisateur dans le bloc planète.

C'est du détail, mais pour info.

Navigateur : chromium.

Non connecté, sans survol :
![hp_planet](https://user-images.githubusercontent.com/1962368/39574526-e3e619e8-4ed7-11e8-8d6d-60a3f5e60540.png)

Non connecté, au survol (à droite) :
![hp_planet_hover](https://user-images.githubusercontent.com/1962368/39574531-e4708c54-4ed7-11e8-94a9-47323186a4d9.png)

Connecté, sans survol :
![hp_planet_connecte](https://user-images.githubusercontent.com/1962368/39574527-e4048824-4ed7-11e8-9cf7-6d9dcfff96a5.png)

Connecté, au survol (à droite) :
![hp_planet_connecte_hover](https://user-images.githubusercontent.com/1962368/39574530-e4437048-4ed7-11e8-9d8b-b119640faa6d.png)

**Comment by FlorisMoriceau** [comment]
Corrigé dans #99 .
