### ISSUE TITLE
Installation impossible.

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#11]
Je n'arrive pas à installer le socle via docker-compose.
La première erreur rencontrée était : 
```
[Composer\Downloader\TransportException]                                                                                                                                           
  Your configuration does not allow connections to http://download.ckeditor.com/link/releases/link_4.6.2.zip. See https://getcomposer.org/doc/06-config.md#secure-http for details. 
```
J'ai donc tenté un `composer update` mais maintenant, j'ai un tas d'erreurs ressembalnt à ça

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "migrate" namespace.       
                                                                                                                                 
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "search-api" namespace.    
                                                                 
/project/scripts/tasks/update_translations.sh: line 4: /project/scripts/script-parameters.local.sh: No such file or directory
                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "locale" namespace.  
```

Je pense que le socle n'est plus à jour dans ses dépendances. Ou alors, il est nécessaire de mettre à jour la doc.

**Comment by FlorentTorregrosa** [comment]
Salut Floris,

Les connections à ckeditor ça je sais d'où ça vient c'est webform qui a besoin de ces librairies et avant ckeditor.com était en http et maintenant en https donc ok, seulement dans le composer.lock c'est encore du http, faut que je règle ça car en modifiant manuellement et faisant un composer udpate, il me remet du http.

Pour les commandes manquantes, là je pense qu'il y a un patch search api qui ne s'est pas appliqué / cache drush vidé. Mais le locale manquant ça aussi c'est bizarre.

Je test ce weekend. Au passage je voulais mettre à jour le socle drupalcamp maintenant que le camp est passé.

Je te tiens au courant lorsque ce sera ok pour moi, si tu voudras bien restester / qu'on voit ça ensemble en direct ce sera mieux pour débugger.

**Comment by FlorentTorregrosa** [comment]
Je viens de pusher pas mal de modifications, dont le passage à config split. Il y a quelques effets de bords sur le front, mais tu m'a dit que tu voulais repartir sur zurb foundation donc j'ai pas plus chercher à tout corriger.
Je teste une install from scratch pour vérifier qu'il ne reste pas d'effet de bord.
Tu peux te refaire le réseau Docker composer avec la commande `docker-compose down` au moins tu auras les dernières versions des images Docker custom (je pense).
Sinon on voit ça dans la réunion pour inclure les nouveaux volontaires développeurs/euses.

**Comment by FlorisMoriceau** [comment]
Alors voici mes manips : 

```
git fetch origin
git checkout 8.x-1.x 
git pull --rebase origin 8.x-1.x
git reset --hard origin/8.x-1.x
HEAD est maintenant à 745a9734 Ignore system.logging as the config created seems to not be from the exported config so it prevents config import.
docker rmi --force $(docker images -a -q)
```

puis 

`docker-compose-up
`
ou, après avoir altéré le `settings.php` et le `local.settings.php` avec les accès à ma base, et en ayant commenté les redis, varnish et tout les services externes, fait un` ./script/install.sh`
je me retrouve toujours avec une erreur émanant de composer.

Des pm-update introuvables, ou des choses comme ça...

**Comment by GoZOo** [comment]
@FlorisMoriceau le `pull - - rebase` est inutile, le `reset - - hard` annule ce qu'il aurait pu faire

**Comment by FlorentTorregrosa** [comment]
@FlorisMoriceau : est-ce que depuis la réunion de mercredi c'est ok pour toi ?

**Comment by FlorisMoriceau** [comment]
Yes c'est bon @FlorentTorregrosa , c'était l'image Docker obsolète qui empêchait le bon déroulement de l'installation.
On peut fermer ce ticket.
