### ISSUE TITLE
Mise à jour de la documentation

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#12]
Dans le Readme.md, le sites/default/settings.local.php n'existe plus.

**Comment by FlorisMoriceau** [comment]
Ajouter pour les "anciens" la commande de mise à jour de l'image docker de @FlorentTorregrosa 

`docker image pull florenttorregrosa/docker-drupal-dev:php7`

**Comment by FlorentTorregrosa** [comment]
L'image sans les librairies de développements : docker image pull florenttorregrosa/docker-drupal:php7
L'image pour Varnish : docker image pull florenttorregrosa/docker-varnish:latest

**Comment by morvans** [comment]
Sinon, on documente de faire

docker-compose pull

avant

docker-compose up

et toutes les images nécessaires seront à jour.

Le 22 novembre 2017 22:56:27 GMT+01:00, Florent Torregrosa <notifications@github.com> a écrit :
>L'image sans les librairies de développements : docker image pull
>florenttorregrosa/docker-drupal:php7
>L'image pour Varnish : docker image pull
>florenttorregrosa/docker-varnish:latest
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Drupal-FR/site-drupalfr/issues/12#issuecomment-346483837

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by FlorisMoriceau** [comment]
Je ne connais pas Docker, je te fais confiance et je 👍

**Comment by FlorisMoriceau** [comment]
@FlorentTorregrosa  : 
> Dans le Readme.md, le sites/default/settings.local.php n'existe plus.

Que doit-on mettre à la place ?

**Comment by FlorisMoriceau** [comment]
## How to create your own admin user : 
* If you are using composer, connect to the web container (something like `docker exec -it drupalfr_web_1 /bin/bash`) and: 
* If you do no use composer, go to your drupal-root folder (`site-drupalfr/www`), and:
```
drush user-create YOUR_USER_NAME --password="YOUR_PASSWORD" --mail="YOUR_MAIL@PROVIDER.DOMAIN"
```

**Comment by FlorentTorregrosa** [comment]
Pour le settings.local.php, son emplacement est désormais : conf/drupal/default/settings.local.php

@FlorisMoriceau : Pour la création du compte user admin, c'est dans un cas général ou tu as eu un problème lors de l'installation ? Normalement les scripts sont faits pour pouvoir fonctionner hors Docker. (il faudrait peut être le rappeler dans la documentation)

`docker exec -it drupalfr_web_1 /bin/bash`

Je mettrai plutôt :

`docker exec -it NOMDUDOSSIER_web_1 /bin/bash`

Sinon par rapport aux commandes Drush, on est sur du Drush 9.x, donc je pense que ce sera du :
`drush user:create`
`drush user:role:add`

ou un truc du genre.

Est-ce qu'on documente également les erreurs auxquelles on s'attend ? :D
* Erreurs lors de l'import migrate des faux users car l'adresse mail example@example.com n'existe pas dans nos listes mailchaimps.
* Erreurs d'indexation des paragraphes dans Search API (une histoire de récursion)
* Lors du cron, Feeds crache, mais c'est dû au Webprofiler (https://www.drupal.org/project/devel/issues/2914657)

Si quelqu'un veut faire un test de commit sur une autre branche pour voir la configuration de protection de la branche 8.x-1.x fonctionne :).

On applique ce même principe de protection de branche sur la 8.x-1.x du socle drupalcamp ?

Les majs de documentation seront également à reporter sur le socle. (juste pour ne pas oublier :))

**Comment by FlorentTorregrosa** [comment]
Il y avait aussi @florent-jousseaume qui m'avait indiqué un warning composer :

> Warning: Ambiguous class resolution, "Drupal\Component\Utility\Random" was found in both "$baseDir . '/www/core/lib/Drupal/Component/Utility/Random.php" and "/project/vendor/drupal/drupal-driver/src/Drupal/Component/Utility/Random.php", the first will be used.

Peut être à documenter.

**Comment by morvans** [comment]
@FlorentTorregrosa pour éviter les problème de détermination du nom du container, on peut recommander d'utiliser ``docker-compose exec`` plutôt que ``docker exec`` : 

`docker-compose exec web /bin/bash`

**Comment by FlorentTorregrosa** [comment]
@morvans : merci pour l'astuce, en effet ça sera bien plus pratique.

**Comment by FlorentTorregrosa** [comment]
Tout ce qui est dans cette issue a été mis dans le Readme.md ou est en train d'être mis dans le wiki sur Github, cf #21.

Je ferme.
