### ISSUE TITLE
Flux RSS planète

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#120]
Fournir un flux RSS du planète.

Vérifier si déjà fait ou non.

**Comment by FlorentTorregrosa** [comment]
Raf indiqué dans la MR: 

Il faudra positionner une icône ou un lien sur la page du planète.

Il me semble que lorsqu'on attache un flux à une vue page, Drupal ajoute automatiquement le header pour que les outils de détection de flux RSS détecte le flux lorsqu'on va sur la page. Là vu qu'on est en bloc de partout via des paragraphes, je ne pense pas qu'il y ait toujours ce système.

À tester.

**Comment by wallon-ines** [comment]
En faite je viens de voir conf/drupal/default/sync/views.view.planet_feed.yml Pourquoi ne pas avoir fait une seule vue ?

**Comment by FlorentTorregrosa** [comment]
Car l'une c'est les node "article du planète" donc table de base node. L'autre c'est les flux qui compose le planète donc table de base "feed".

Pas possible de faire une vue avec des affichages sur 2 tables de base différentes.

PS: bon du coup on discute dans l'issue ou la PR ? :D

**Comment by wallon-ines** [comment]
A l'issue de la PR on discutera ;) ====>[ ]
