### ISSUE TITLE
REPO :  drupal.fr V8 + ZURB Foundation

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#15]
Je pense que : 
"for reasons"
Il serait préférable de déplacer une fois la branche ZF en alpha, voire même avant, le projet Drupal/fr V8 sur un repo à part...

La taille du bébé devient critique, et en plus, vraiment, on ne parle pas de la même chose... les diff sur develop sont tout pourris, ce n'est pas intuitif de faire des MR, etc...

**Comment by FlorentTorregrosa** [comment]
Salut Floris,

Je comprends ta demande.

Par contre je trouverai dommage de perdre l'historique des contributions sur les sites D7 et D6.

On obtiendrait donc sur le long terme 2 dépôts ? site-drupalfr (site actuel) et drupalfr (site D8 puis les futures versions) ?

Si c'est uniquement pour les diff sur les Merge requests, on peut indiquer que la branche principale est la 8.x-1.x et ce sera plus pratique.

**Comment by FlorisMoriceau** [comment]
Salut, 
Inutile de supprimer le repo existant mais comme tu le dit, déplacer la branche 8x1x sur un nouveau repo afin de diminuer la taille de ce dernier lors du clone, mais également améliorer la clarté des issues, MR et autres, entre la version 7 et la version 8.

**Comment by morvans** [comment]
Est-ce que l'option --single-branch lors du clone ne résoudrait pas les
problèmes de taille de repository (pour ceux pour qui c'est un problème) ?

**Comment by FlorisMoriceau** [comment]
Je ne connaissais pas cette option et n'avais pas cherché dans ce sens, mais pourquoi pas.

**Comment by FlorisMoriceau** [comment]
Du coup, je vois que le wiki du GitHub est vide.
Je peux le prendre pour mettre la doc de la 8.x-1.x dedans ?

**Comment by FlorentTorregrosa** [comment]
Vas y. On pourra faire une doc plus complète que dans le README sans qu'il devienne trop gros.

**Comment by FlorisMoriceau** [comment]
Impec !
