### ISSUE TITLE
Update Contrib Module EU Cookie Compliance

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#159]
https://www.drupal.org/sa-contrib-2018-047

**Comment by FlorisMoriceau** [comment]
De plus, est-ce que l'on utilise celui-ci ? : 

https://www.drupal.org/sa-contrib-2018-046

**Comment by FlorentTorregrosa** [comment]
On n'utilise pas le deuxième.

**Comment by FlorentTorregrosa** [comment]
C'est push sur la MR #158. Car vu qu'elle touche déjà Composer et la conf. J'avais pas envie d'avoir un conflit Git.
