### ISSUE TITLE
TOPBAR - MAIN MENU

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#16]
Travailler le fichier ` _menu_main.scss` afin de lui donner le comportement attendu.

**Maquette :** https://projects.invisionapp.com/share/HZ9S0P5C8#/screens/211677697

**Interactivité :** 

- Le menu `LVL 0` est disposé sur une ligne à l'horizontal grâce à `flex`
- Au survol d'un élément, cela ouvre le menu `LVL 1` associé à l'élément survolé dans une ligne en dessous. Ce menu a un `background-color : $drupal-blue-light`. Du code commenté vous indiquera comment cela fonctionnait avec bootstrap. Il faut juste l'adapter.
- Lors de l'ouverture d'une page dont issue d'un élément de menu `LVL 1`, le sous menu doit être ouvert et visible, et l'élément actif en gras. Si possible, mettre en gras le libellé l'élément parent.

**Comment by FlorentTorregrosa** [comment]
C'est pour des raisons de performances que tu veux éviter de le loader 2 fois ? Je ne sais pas si ça ferait réellement un écart de perf.

En soit le module a l'air sympathique, dommage qu'il ne soit pas sur Drupal.org, il manque un peu de nettoyage, mais surtout, j'ai pas l'impression qu'il soit bien pour masquer des régions.

Je ferai plutôt un plugin de condition de bloc et donc avec gestion du cache derrière via le plugin. Il y aurait donc variation de cache en fonction d'être sous mobile ou non, et c'est là où je me demande si en terme de performance ça ne risque pas d'avoir un effet même négatif, plutôt qu'un bloc dont le rendu est déjà en cache, juste afficher 2 fois sur la page.

**Comment by FlorisMoriceau** [comment]
C'était surtout pour la SEO.
Avoir deux fois le même menu, je crois que ce n'est pas terrible.

L'avis d'un expert SEO genre @simongeorges serait le bienvenu.

**Comment by simongeorges** [comment]
@FlorisMoriceau Ce type de module va toujours foirer un jour ou l'autre (il n'est pas en accord avec tes breakpoints de theme, par exemple, à mon avis, donc ça risque de faire des trucs chelou) : "It uses the User-Agent string combined with specific HTTP headers to detect the mobile environment" signifie "je code comme en 2010".

**Comment by FlorisMoriceau** [comment]
Super, merci @simongeorges .

Bon, on clos le ticket, et on en ouvrira un autre sur ce sujet au besoin.
