### ISSUE TITLE
[Migrate] Assets des maquettes

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#162]
### Ajouter dans les fichiers CSV d'import les différents assets (Images) et le texte défini dans les maquettes, afin de faciliter la future contribution de contenus.

**Procédure :** 
- Récupérer toutes les images et les nommer de manière explicite (Source : [02 Maquette Html V01.zip](https://github.com/Drupal-FR/site-drupalfr/files/2200312/02.Maquette.Html.V01.zip) )
- Les copier dans `/www/modules/custom/drupalfr_migrate/migrations/data/files`
- Définir la création d'un nouveau fichier dans `file.csv`
- Définir la création d'une nouvelle entité média dans `media.csv`
- Appliquer les ID des média nouvellement créés dans `paragraph.csv`
- Si vous le souhaitez, intégrez également le texte.

**Comment by FlorisMoriceau** [comment]
Je reopen, j'avais pas vu qu'il en manquais plein. :(

**Comment by FlorisMoriceau** [comment]
@mouna16 On compte sur toi !

**Comment by FlorisMoriceau** [comment]
@Pomliane , libre à toi de réfléchir au contenu des pages, et de proposer du contenu via les fichiers CSV de migration.

(D'expérience, il est plus facile de copier coller le contenu HTML des paragraphs via LibreOffice Calc, qui auto-échappe les caractères accentués et les signes de ponctuation. )

**Comment by wallon-ines** [comment]
@FlorisMoriceau sur Slack :  "On clos le ticket. On mettra à la main les choses voulues."
