### ISSUE TITLE
[Intégration] Page Offres d'Emploi

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#165]
Maquette : [ICI](https://projects.invisionapp.com/share/HZ9S0P5C8#/screens/211677706)

**Comment by FlorentTorregrosa** [comment]
Spécifications par rapport à la maquette : https://github.com/Drupal-FR/site-drupalfr/wiki/page-offres-d%27emploi

**Comment by wallon-ines** [comment]
Rajouter un bouton "Retour à la liste" sur la page qui détail l'annonce

**Comment by wallon-ines** [comment]
centrer (medium-12) la page node/add/job_offer (pour les non admin)
