### ISSUE TITLE
Amélioration de l'utilisation des preprocess

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#166]
En amélioration, pour que le code soit plus "propre" et pour éviter de faire certains preprocess.

* ~~drupalfr_paragraph_preprocess_paragraph~~ : voir si la partie `// Allow to wrap the paragraph into a link.` ne pourrait pas être remplacé par https://www.drupal.org/project/linked_field.
* ~~drupalfr_planet_preprocess_node~~ : passer par des extra field si possible.
* ~~drupalfr_release_preprocess_node~~ : passer par un extra field si possible.
* ~~drupalfr_release_cron~~ : pour la partie process de la queue, créer un queue worker. Voir peut être aussi l'API d'advanced queue ce qu'elle permet, vu qu'on a le module pour commerce license autant s'en servir aussi.
* ~~drupalfr_showcase_preprocess_field__node__field_showcase_media~~ : remplacer par linked field si possible.
* ~~drupalfr_user_preprocess_use~~r : passer par un extra field si possible.
* ~~drupalfr_local_group_preprocess_node~~ : faire un formateur de champ.

**Comment by wallon-ines** [comment]
sur drupalfr_paragraph_preprocess_paragraph il me fait de la merde
j'ai la balise <p> avant le <a> et je galère à faire l'inverse
![capture d ecran_2018-08-11_12-51-47](https://user-images.githubusercontent.com/11542186/43991083-5e394df6-9d65-11e8-8f3e-9c89a5fa99be.png)

**Comment by wallon-ines** [comment]
![capture d ecran_2018-08-11_12-53-11](https://user-images.githubusercontent.com/11542186/43991091-852fa806-9d65-11e8-9429-3b52cc183b73.png)

**Comment by wallon-ines** [comment]
extra field Planet OK

**Comment by wallon-ines** [comment]
DrupalfrRelease OK

**Comment by FlorentTorregrosa** [comment]
Comme discuter ensemble, je vais chercher de mon côté pour m'entraîner et on comparera les résultats.

**Comment by FlorentTorregrosa** [comment]
Je viens de reproduire pour le paragraphe banner.

Le problème vient du fait qu'avec linked_field la balise "a" est juste avant la valeur du champ (dans les div field-items et field-item) et comme il s'agit d'un RTE, il y a une balise "p". Et un "p" ne peut pas être dans un "a" directement. Alors qu'avec les preprocess actuels, la balise "a" est à l'extérieur des div et là ça passe.

On laisse ce point de côté, en attendant un retour de Floris. On pourrait potentiellement changer le RTE en text long et plain.

**Comment by FlorentTorregrosa** [comment]
@wallon-ines : ok pour moi, j'ai fait les différentes merge request. À chaque fois je repars de #167.

Je te laisse jeter un oeil au code et on verra pour les merges.

**Comment by wallon-ines** [comment]
c'est bon pour moi.

je viens de delete la branch distante
