### ISSUE TITLE
Code quality tools.

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#168]
@FlorisMoriceau, je viens de pusher des scripts d'analyse de la qualité du code :
* https://github.com/FlorentTorregrosa/docker-drupal-project/commit/3a62a3b96edaca9df675a1c1bf49a98cf2756a26
* https://github.com/FlorentTorregrosa/docker-drupal-project/commit/6753c3496fc089ffa17a758d8bbcb09ebeb921d9
* https://github.com/FlorentTorregrosa/docker-drupal-project/commit/8e624a230b7cca66b41f7b6690b5b97366e9edbc

J'ai fait un mélange :
* des fichiers de settings du noyau,
* de https://github.com/Smile-SA/grunt-drupal-code-quality : en passant à Gulp et en retirant la nécessité du chemin absolu vers l'installation du projet
* du gulpfile du starter kit de Zurb : en retirant la partie compilation du SASS et en augmentant le niveau des warnings afin d'empêcher de commiter en cas de warning.

Serait-il possible d'avoir ton retour dessus s'il te plaît ?

Car j'aimerai l'intégrer aux dépôt site-drupalfr et socle-drupalcamp.

Et la config du starter kit Zurb reste pensée pour le thème et pas pour les modules qui vont avec et il n'y a pas d'analyse du CSS ou de PHP.

Bon après du coup le check complet prend presque 1 minute sur peu de fichiers... Il faudra que j'améliore pour ne prendre en compte que les fichiers qui vont être commités.

Je pense aussi que l'on peut améliorer le package.json du thème drupal_france en ajoutant :
```json
  "engines": {
    "node": "8.11.x"
  },
```
pour être sûr que le package-lock.json ne va pas être modifié selon la version de nodejs utilisée.

Du coup, j'ai également Github qui me signale une faille de sécurité potentielle sur un des packets npm...

**Comment by FlorisMoriceau** [comment]
Alors, pour te répondre : 100% OK sur le principe.
Mais la stack SASS / Foundation embarquée dans le theme enfant propose déjà un outil de linting des feuilles de style lors de la compilation.

Je dois t'avouer que je n'ai pas regardé en profondeur, ni testé tes scripts de quality-linting avant de répondre, mais j'ai cru remarqué que ton .csslint n'avait rien en commun avec mon .sass-lint.

J'aimerai beaucoup empêcher le commit en cas de warning SASS. 
Il va falloir que je prenne le temps de faire matcher les fichiers de config de ces deux linters.

Pour le JS, j'ai lâché l'affaire pendant quelques années, et m'y remets aujourd'hui. Avec toutes ces histoires de ES6, ES7, ES2017, de Babel, et touti quanti, je ne peux pour le moment pas me positionner sur une manière de linter les assets JS venues du theme.
J'ai cru voir un tweet de drupal core stipulant qu'un linter avait été choisi.

Peut-être pourrions-nous l'implémenter ?

**Comment by FlorentTorregrosa** [comment]
Merci pour ton retour.

Avant de tester, attend, j'ai des améliorations à faire suite à échanges au sein de Smile et pour m'en servir actuellement sur un projet.

Oui, le starterkit de Zurb a son linter, mais justement je veux l'extraire pour qu'il fonctionne en dehors.

**Comment by FlorentTorregrosa** [comment]
Je ferme, je mettrai à jour lorsque ce sera ok sur ma stack perso.
