### ISSUE TITLE
template de champ avec field__items

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#171]
Il y a des template de champs avec des classes field__items, sans doute du passage de Bootstrap à Zurb car j'avais vu passer dans le thème Bootstrap la correction de cette classe en field--items.

Que veut-tu que l'on fasse ?

**Comment by FlorisMoriceau** [comment]
Heuuu...

Tu peux me donner les noms de fichiers incriminés stp ?
Que je te réponde avec précision.

Merci d'avance.

**Comment by FlorentTorregrosa** [comment]
Pour l'instant tous les templates fields que l'on a dans le thème https://github.com/Drupal-FR/site-drupalfr/tree/8.x-1.x/www/themes/custom/drupal_france/templates/field

**Comment by FlorentTorregrosa** [comment]
#190 créée.
