### ISSUE TITLE
Type de contenu release : type de version masquée

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#175]
Pourquoi dans le template des release (page téléchargement), on masque le type de version ?

```twig
{{ content|without(..., 'field_release_type', ...) }}
```

**Comment by FlorisMoriceau** [comment]
Heu...

Tout simplement pour matcher la [maquette](https://projects.invisionapp.com/share/HZ9S0P5C8#/screens/211677707). Mais, j'ai peut être raté un truc.

**Comment by FlorentTorregrosa** [comment]
Ok. Je pense qu'on va afficher cette information si présente. Juste avant le texte, car le texte lui n'est pas importé automatiquement.

**Comment by FlorentTorregrosa** [comment]
@FlorisMoriceau je te réassigne le ticket ?

**Comment by FlorentTorregrosa** [comment]
#188 créée.
