### ISSUE TITLE
CONTENT TYPE : Banner

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#19]
Idée : avoir une zone en pleine largeur de page (hors du contexte de la page) qui se place au dessus du top menu, et qui soit sur toutes les pages.
On y mettre une image ou une couleur de fond avec un lien (ex. la bannière camp)

Mise en place : 

- **Background image** : _Responsive Image_
- **Background color** : _Unformatted text_ (+ color picker)
- **URL** : _Link_
- **Button Label**
- **Text** : _Formatted short text_
- **Text-color** : _List_ ['dark', 'light']
  Si Dark, couleur du texte : $black + text shadow à base de $white, boutton avec classes "primary highlight"
  Si Light couleur du texte : $white + text shadow à base de $black, boutton avec classes "inverted, hightlight"

ℹ️ Tous les champs sont obligatoires, sauf **Background image**

## Afficher le bloc

- en haut de la page, au dessus du menu

**Comment by FlorentTorregrosa** [comment]
Salut Floris,

C'est pour pouvoir mettre la bannière sur toutes les pages que tu veux passer par un type de contenu ?

Car il y a déjà un type de paragraphe "Bannière"

**Comment by asplamagnifique** [comment]
Idem Florent, un type de contenu pour une bannière c'est sans doute de trop, alors que nous avons des pages paragraph qui sont modulables.

**Comment by asplamagnifique** [comment]
Idée : avoir une zone en pleine largeur de page (hors du contexte de la page) qui se place au dessus du top menu, et qui soit sur toutes les pages.
On y mettre une image ou une couleur de fond avec un lien (ex. la bannière camp)

**Comment by mouna16** [comment]
Je m'occupe de ce ticket
