### ISSUE TITLE
Mise en place de la page médiatheque 

### ISSUE THREAD

**Issue by wallon-ines** [Drupal-FR/site-drupalfr#205]
- Mise en place d'un filtre exposé basé sur la taxo "media_tags" (à créer)
- Faire le theming de la page

**Comment by FlorentTorregrosa** [comment]
changer le nom machine de la vue media_library (pour ne pas être incompatible avec le media_library du noyau)

**Comment by FlorisMoriceau** [comment]
Sachant que l'on vient de "dé-publier" cette page sur le D7, ce ticket est-il toujours d'actualité ?
Si oui, ce n'est surement pas dans le périmètre MVP.
Si non, on ferme ce ticket.

**Comment by FlorentTorregrosa** [comment]
Ticket à garder je pense et à ne pas mettre dans le MVP.

**Comment by wallon-ines** [comment]
faut qu'on ferme ce ticket à mon avis
