### ISSUE TITLE
DOC : Wiki

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#21]
Déplacer le contenu des différents Readme.md de la branche 8.x-1.x vers le wiki de GitHub.

Au sommaire : 

- Comment contribuer
- Installation
  - Avec Docker
  - Avec un WAMP / LAMP / MAMP
- Les branches
- Le workflow
- Back-End
  -  ...
- Front-End
  - ZURB Foundation
  - SCSS + Lint
  - Variables et Charte Graphique

[...] To Be Continued

**Comment by FlorentTorregrosa** [comment]
Arf, c'est un peu light le wiki Github, pas possible de faire de l'arborescence de page. Tant pis, on fera avec.

**Comment by FlorentTorregrosa** [comment]
Pages du wiki initialisées.

Par contre, je ne trouve pas le Wiki Github super pratique pour hiérarchiser les pages.

Je me demande si faire des pages comme https://github.com/FlorentTorregrosa/docker-drupal-project/tree/8.x/docs, ne serait pas mieux. Au moins ça suit vraiment les évolutions du code.
