### ISSUE TITLE
Solr Is ?

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#219]
Un appel à Solr est bloquant, entre le `docker-compose-common.yml` et le `docker-compose.yml`

```
 
 ✘ floris@*********  ~/Projects/drupal/drupal.fr > 8.x-1.x > docker-compose -f docker-compose.yml pull 
ERROR: Cannot extend service 'solr' in /Users/floris/Projects/drupal/drupal.fr/docker-compose-common.yml: Service not found
```

**Comment by FlorisMoriceau** [comment]
Je remarque que mon `git status` ne m'indique pas la suppression du serveur solr dans mon `docker-compose.yml`. 
Si ce fichier est propre à l'environement du client, il faut faire une MaJ de la DOC.

**Comment by FlorentTorregrosa** [comment]
Il faut faire une maj du fichier docker-compose.yml, regarder le example.docker-compose.yml https://github.com/Drupal-FR/site-drupalfr/commit/41ba8e02a6efa5b6d7dc94309dcb7521d46ec095

https://github.com/Drupal-FR/site-drupalfr/issues/213

tu peux retirer l'entrée solr de ton docker-compose.yml et faire 'docker ps -a' pour repérer l'ancien conteneur solr et le supprimer avec un 'docker rm ID_du_conteneur'

**Comment by FlorisMoriceau** [comment]
Merci.
C'est la procédure que j'ai suivie.
