### ISSUE TITLE
Export csv pour migrate

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#221]
Est-ce que ce ne serait pas pratique de mettre en place des exports csv via views_data_export pour régénérer les fichiers pour migrate ?

Comme ça lorsque quelqu'un contribue sur son site ou sur la preprod, ce sera assez simple de s'exporter les CSV dans le bon format.

@FlorisMoriceau qu'en penses-tu ?

**Comment by FlorisMoriceau** [comment]
100% `+1`

**Comment by wallon-ines** [comment]
Je valide également

**Comment by wallon-ines** [comment]
Tester le module de Fabrice, voir si ça fait le taf https://www.drupal.org/project/entity_export_csv

**Comment by wallon-ines** [comment]
Ça serai pas mieux de partir sur entity staging plutot que de faire un custom export csv ?

**Comment by wallon-ines** [comment]
Étant donnée qu'on va jouer avec l'export de base entre préprod et prod, je vais fermer ce ticket, qu'en pensez vous ?

**Comment by FlorentTorregrosa** [comment]
Tu peux fermer le ticket. Merci d'avoir demandé. :)

**Comment by wallon-ines** [comment]
#OneTeam ;)
