### ISSUE TITLE
MODULE : Add Color field + color picker

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#23]
Afin de faciliter le site building, nous aurions besoin de créer des champs "couleur".

Un champ texte ne répondant valide qu'au format d'une couleur en hexadécimal à 6 digits.

@Artusamak , j'ai vu que tu étais owner du module colorfield pour D7.
Le module https://www.drupal.org/project/color_field pourrait-il correspondre pour notre cas d'usage ?

**Comment by Artusamak** [comment]
Ça fera le job, oui.

**Comment by FlorentTorregrosa** [comment]
Pull request créée.
