### ISSUE TITLE
Mise à jours des dépendances front

### ISSUE THREAD

**Issue by wallon-ines** [Drupal-FR/site-drupalfr#247]
Fixer les alertes de sécurité dans le package-lock.json  et le yarn.lock

voir : https://github.com/Drupal-FR/site-drupalfr/network/alerts

**Comment by FlorisMoriceau** [comment]
Alors, 
Cette issue est un marathon de sécurisation.
Les package-lock.json et les yarn.lock sont générés via npm ou yarn en prenant en compte les dépendances, en cascades, de chacun des éléments dans node_modules.

Afin de corriger le tir, il ne suffit pas de modifier le .lock. il faut être sur que chacun des modules nécessaires au fonctionnement de la stack drupalfr ait en dépendance des versions à jour, et ainsi de suite.

Je n'ai pas envie de mettre le doigt la dedans là maintenant. Ca pourrait nécessiter un travail de contrib dans le core de drupal si on voulait être nickel à la vue de GitHub.
