### ISSUE TITLE
Problème de z-index sur la page des groupes locaux

### ISSUE THREAD

**Issue by wallon-ines** [Drupal-FR/site-drupalfr#251]
Dans la page "communaute/groupes-locaux", le menu passe en dessous de la carte 

À modifier : 
```
.leaflet-container {
    z-index: -1000;
}
```

**Comment by FlorisMoriceau** [comment]
Tu parles de ça : 
![image](https://user-images.githubusercontent.com/1312944/87235967-24c36880-c3e3-11ea-80ef-e4c0ff1b949e.png)

**Comment by wallon-ines** [comment]
oui par exemple 
Mais je pensais au menu, 
![20200712_105017](https://user-images.githubusercontent.com/11542186/87242521-bbb51280-c42d-11ea-8156-a6abffca048c.jpg)

**Comment by FlorisMoriceau** [comment]
OK. C'est réparé.

Pour info, c'est mal de gérer des z-index négatifs. C'est très risqué pour la maintenance des couches du DOM, et parfois mal interprété par les navigateurs.
