### ISSUE TITLE
[BO] Configurer Search API

### ISSUE THREAD

**Issue by wallon-ines** [Drupal-FR/site-drupalfr#265]
CT à rechercher :

* Événements
* Actualité
* Page
* Article du planète

**Comment by wallon-ines** [comment]
@FlorisMoriceau Doit on mettre un résultat par défaut si pas de valeurs renseigné dans le champ recherche ?

**Comment by FlorisMoriceau** [comment]
Non, si rien est recherché, pas de résultats.
