### ISSUE TITLE
Docker : Traefik

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#27]
J'aimerai bien mettre en place Traefik poour le site Drupalfr V8 (a minimapour les environnements de développement), car c'est qu'en même plus agréable d'accéder à ses sites locaux via un nom de domaine que par une IP+port. Et ça permet d'avoir la session qui déconne pas d'un site à l'autre, sinon avec l'IP, la session est invalidée.

@morvans, toi qui a beaucoup plus d'expérience que moi sur le sujet, est-ce que la conf suivante est ok ? :
* https://github.com/FlorentTorregrosa/docker-drupal-project/tree/8.x/conf/traefik
* https://github.com/FlorentTorregrosa/docker-drupal-project/blob/8.x/example.docker-compose.yml
* https://github.com/FlorentTorregrosa/docker-drupal-project/blob/8.x/docker-compose-common.yml
* https://assos.centrale-marseille.fr/ftorregrosa/book/handbook/dnsmasq

Par contre ce que je crains, c'est que ça mette une barrière pour les personnes débutant en Docker. De plus, je ne sais pas si les personnes sous OSX ou Windows pourront faire la manipulation de DNSMasq.

PS : si c'est mis en place pour Drupalfr V8, ce sera mis en place également pour le socle Drupalcamp :)

**Comment by GoZOo** [comment]
Pas de soucis pour dnsmasq sous osx, et il me semble que c'est bon sous Windows également, les 2 ont ce qu'il faut

**Comment by FlorentTorregrosa** [comment]
Merci @GoZOo pour ton retour.

De plus j'ai aussi pensé qu'au pire, il est possible de mettre les entrées directement dans le /etc/hosts (ou équivalent Windows) si la personne n'a pas envie de s'embêter à s'installer ce logiciel.

Le dnsmasq ou tout autre DNS n'est là que pour avoir un wildcard et moins s'embêter.

**Comment by morvans** [comment]
L'utilisation des networks dans la config docker-compose complique (inutilement, selon moi) le projet.
Dans l'usage que je fais quotidiennement de traefik en développement, il suffit de mettre le label traefik.frontend.rule.
@FlorentTorregrosa tu pourrais expliquer pourquoi tu en est arrivé à cette config ?

**Comment by FlorentTorregrosa** [comment]
Ah, si les networks sont optionnels (en mode développement en tout cas) c'est mieux car en effet ça embrouille plus qu'autre chose.
Pourquoi j'ai mis les networks, parce que j'avais regardé la doc de Traefik et que j'étais arrivé à ce résultat lorsque ce que je voulais faire fonctionnait, j'avais fait un mélange des conf suivantes :
* https://docs.traefik.io/#__code_2
* https://docs.traefik.io/#__code_3
* https://docs.traefik.io/user-guide/docker-and-lets-encrypt/

**Comment by FlorentTorregrosa** [comment]
Suite de l'issue dans l'issue #42 et la PR #43.

Je ferme cette issue.
