### ISSUE TITLE
Mettre les release D9 en avant 

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#308]
Sur la page /decouvrir/telechargements , il faudrait mettre en avant les release 9.x en premier, puis les release 8.x, en enfin les releases 7.x

**Comment by wallon-ines** [comment]
c'est l'url qui est plus bonne
faut remplacer https://updates.drupal.org/release-history/drupal/8.x par https://updates.drupal.org/release-history/drupal/current
