### ISSUE TITLE
Vérification intégration ZURB foundation

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#31]
Vu qu'il n'y a pas de nodejs sur les serveurs de preprod et prod et qu'on déploit avec git pull et composer install, etc.

Il faut voir s'il ne faut pas télécharger la librarie foundation-sites par Composer plutôt que par npm. Surtout pour le JS, car le CSS compilé est versionné.

**Comment by FlorentTorregrosa** [comment]
Je préfère laisser cette issue en stand by, voir si niveau theming c'est ok dans l'état actuel.

Il y a un point que je ne comprends pas, dans www/themes/custom/drupal_france/scss/drupal_france.scss, il y a :
```scss
// Core
// The following imports bootstrap the theme.
@import 'foundation';
@import 'motion-ui';
```
Seulement il n'y a pas de fichier foundation.scss et motion-ui.scss dans ce dossier.

Je suspecte que dans www/themes/custom/drupal_france/gulpfile.js :
```js
// Define the node-scss configuration.
options.scss = {
  importer: importOnce,
  outputStyle: 'compressed',
  lintIgnore: 'scss/_settings.scss',
  includePaths: [
    options.rootPath.project + 'node_modules/foundation-sites/scss',
    options.rootPath.project + 'node_modules/motion-ui/src'
  ],
};
```
le includePaths fait que ça marche par "magie".

Je reste sceptique sur les fichiers JS contenus dans :
* www/themes/custom/drupal_france/node_modules/foundation-sites/dist/js
* www/themes/custom/drupal_france/node_modules/motion-ui

mais peut être qu'on en a pas besoin car ils sont versionnés dans www/themes/contrib/zurb_foundation/js

Dommage que le thème de base ait la librairie ZURB Foundation en partie versionnée.

Par contre j'espère que le thème contrib va se stabiliser et sortir de nouvelles versions. Autant en termes de fonctionnalités, ZURB foundation 6 for site est devant Bootstrap 3, par contre en termes de stabilité, le thème contrib Bootstrap est plus abouti je pense.

Si quelqu'un peut me répondre sur le point que je ne comprends pas, on peut fermer l'issue.

**Comment by FlorisMoriceau** [comment]
Alors, 
c'est bien le `includePaths` qui fait que ça marche.
Moi aussi j'ai eu du mal au début.

En ce qui concerne les assets contenus dans le theme contrib, en fait, ils ne sont pas utilisés. En effet, le premier truc qu'on fait lors du `npm install` du STARTER_KIT, c'est d'installer foundation-sites dans son theme enfant.
Pourquoi ne pas aller les chercher directement dans le thème contrib ?
Parce que ZF va plus vite que Drupal, et que le thème est encore en alpha.

En fait, je me sert du thème contrib comme coquille vide, je n'ai pas envie de prendre de risques.

Un jour, quand j'aurai le temps, j'irai filer un coup de main sur ce projet.

**Comment by FlorentTorregrosa** [comment]
Ok.
