### ISSUE TITLE
Ajout d'un fil d'Ariane sur les pages

### ISSUE THREAD

**Issue by asplamagnifique2** [Drupal-FR/site-drupalfr#318]
Je me rend compte de ça sur les pages évènements, mais on ne peut pas retourner à la liste des events depuis une page.
Je pense qu'il est logique de le placer sous le menu principal avant le début de la page (et/ou de sa bannière)

Proposition de composition du fil d'ariane sur les pages

- *Découvrir* : Accueil/
- - Découvrir drupal : Accueil / Decouvrir
- - Télécharger Accueil / Découvrir
-  *Assistance* Accueil
- - Slack Accueil/Assistance
- - Documentation Accueil/Assistance
- - Contact : Accueil/Assistance
- *Emploi* : Accueil (est ce que ce label est définitif ?)
- - Offres d'emploi : Accueil / Emploi 
- - - une offre d'emploi : Accueil / Emploi / Offres d'emploi
- - Annuaire : Accueil / Emploi
- *Communauté* : Acceuil/
- - Présentation  : Accueil / Communauté 
- - Meetup : Accueil / Communauté 
- - Les groupes locaux : Accueil / Communauté 
- - Planète Drupal : Accueil / Communauté 
- - Les membres : Accueil / Communauté 
- *L'association* : Accueil
- - Présentation : Accueil / L'association
- - Adhérer : Accueil / L'association
- - Actualités : Accueil / L'association
- - - Page d'une actualité : Accueil / L'association / Actualités
- - Les évènements : Accueil / L'association
- - - Page d'un event : Accueil / L'association / Les évènements
- - Contact : Accueil / L'association

**Comment by wallon-ines** [comment]
mergé sur l'instance develop
