### ISSUE TITLE
Liste des téléchargements - Limiter le nombre d'items dans la liste

### ISSUE THREAD

**Issue by asplamagnifique2** [Drupal-FR/site-drupalfr#321]
Je ne pense pas qu'on ait besoin de lister toutes les releases de D8 et D9.
- se limiter à une page sans pagination je pense que ça suffit  (on a toutes les alpha, and co, qui va aller voir ça ?)
- - du coup peut être prévoir un cron de nettoyage des versions passées si plus de x dispo (j'imagine que les versions dispo sont importées automatiquemnt)
- est ce qu'on pourrait ajouter un onglet ou élément pour filtrer sur une version d8 ou d9 si on garde tout.

**Comment by wallon-ines** [comment]
Mise sur dévelop
