### ISSUE TITLE
Contribution dans le BO - soucis d'espace sur la page assistance

### ISSUE THREAD

**Issue by asplamagnifique2** [Drupal-FR/site-drupalfr#322]
<img width="1290" alt="Capture d’écran 2021-03-23 à 15 38 19" src="https://user-images.githubusercontent.com/77117428/112164040-dd39e100-8bed-11eb-888a-66d4a904e695.png">

Est ce qu'on peut ne pas afficher la colonne dans le BO mais plutôt en dessous des champs du form pour ce type de contenu ? Parce que là ... la contribution des textes de FAQ c'est pas hyper fonctionnel
https://www.staging-5em2ouy-3xskdxte63ugo.eu-4.platformsh.site/node/16/edit

**Comment by wallon-ines** [comment]
Effectivement, faudrait que j'install le module de @flocondetoile https://www.drupal.org/project/meta_position

**Comment by FlorisMoriceau** [comment]
On est plutôt sur un "Nice to have for admin" sur ce ticket, si je ne m'abuse. On va essayer de le pousser en V+1, dans le but de sortir du contenu (bien mal contribué je l'accorde) en premier lieu.

**Comment by asplamagnifique2** [comment]
Avec le passage à Gin, j'ai un soucis de poignées de Drag'N'drop x3 (sur des projets je sais qu'on avait regardé ces issues     https://www.drupal.org/project/drupal/issues/3092181 ,     https://www.drupal.org/project/drupal/issues/3145188 ,     https://www.drupal.org/project/drupal/issues/2937996 )

**Comment by wallon-ines** [comment]
Fixé en horizontal
