### ISSUE TITLE
CONTENT Homepage : Découvrir Drupal

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#34]
Passez en ZF la zone "Découvrir Drupal"

**Comment by FlorentTorregrosa** [comment]
Salut Floris,

J'ai vu tes issues et merge request.

Je les regarderai calmement ce soir.

Merci.

**Comment by FlorentTorregrosa** [comment]
OK, pour moi après test. Sera mergé dans #37
