### ISSUE TITLE
Docker: simplification docker-compose.yml

### ISSUE THREAD

**Issue by morvans** [Drupal-FR/site-drupalfr#42]
Hello,

J'aimerais bien qu'on simplifie la configuration docker-compose.yml.

- supprimer le docker-compose-common.yml qui de toute façon n'est pas partagé avec d'autres configs et qui fournit des définitions de services qu'on utilise pas. les extends ne sont de toutes façon toujours pas supportés par le format version 3.
- fournir un docker-compose.yml (au lieu d'un exemple) en utilisant des variables avec des valeurs par défaut qu'on pourra surcharger localement avec .env (on fournirait plutôt un env.exemple ou alors on documenterait ça dans le README.

l'idée est d'arriver à un workflow le plus simple possible pour le nouveau contributeur : 
- git clone ...
- docker-compose up

**Comment by morvans** [comment]
Si quelqu'un voit un intérêt à la construction actuelle (modification fréquente et conséquente du docker-compose.yml local, par exemple) j'aimerais avoir son point de vue :)

**Comment by FlorentTorregrosa** [comment]
Merci Simon pour ta PR et ta suggestion.

En fait je ne connaissais pas l'usage du fichier .env, donc j'ai fait avec ce que je pensais être le mieux par rapport à mes connaissances et un peu comme le fait Drupal avec le fichier example.sites.php et pour laisser la possibilité aux personnes d'adapter leur conf.

Mais c'est vrai que c'est contraignant les adaptations du docker-compose.yml à reporter manuellement. Désolé.

Je suppose que les outils d'intégration continue, quand dans leur interface tu peux paramétrer des variables d'environnements, ils génèrent un fichier .env ? et du coup tu as une conf adaptable par env et iso que ce soit un environnement ou un environnement temporaire généré par un outil de CI ?

Je testerai ta PR plus en détail ce weekend ou le prochain.

Merci.

**Comment by FlorentTorregrosa** [comment]
En train de revoir la doc, je vais m'occuper de cela au passage.

**Comment by FlorentTorregrosa** [comment]
Première étape : fournir un début d'intégration Traefik mergé.

Reste à créer des variables dans le .env et à s'en servir (connexion à la BDD, Environnement pour les scripts, etc.)
