### ISSUE TITLE
[MySQL] Connexion impossible à la BDD lors de l'installation

### ISSUE THREAD

**Issue by mouna16** [Drupal-FR/site-drupalfr#45]
Bonjour, 

En voulant installer le projet, via Docker, sur Windows 10, j'ai cette erreur, qui m'empêche d'installer la BDD dans le container `mysql`

` [error]  Failed to create database: ERROR 1045 (28000): Access denied for user 'drupal'@'sitedrupalfr_web_1.sitedrupalfr_default' (using password: YES)`

Pourriez-vous m'aider svp ?

Merci d'avance.

**Comment by FlorentTorregrosa** [comment]
Bonjour,

N'utilisant pas Windows, je n'ai pas répondu auparavant.

Mais en voyant le message d'erreur, il me semble que les informations de connexion ne sont pas celles attendues [par défaut](https://github.com/Drupal-FR/site-drupalfr/blob/8.x-1.x/conf/drupal/default/example.settings.local.php).

En utilisant Docker Compose, les conteneurs devraient être initialisés et pouvoir communiquer entre eux.

Sinon, il faut ajuster votre fichier settings.local.php avec les informations de connexion pour votre environnement.

Cordialement,

**Comment by mouna16** [comment]
Bonjour Florent,

Merci pour ta réponse.

 J'ai les même informations celle de par défaut.
toujours j'ai le même problème. 
"Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'drupal'@'sitedrupalfr_web_1.sitedrupalfr_default' (using password: YES) in Drupal\Core\Database\Driver\mysql\Connection::open() (line 156 of /project/www/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php)."

**Comment by FlorentTorregrosa** [comment]
On a réglé le problème ensemble.

Pour partager aux autres.

Cela venait d'un problème de permissions de fichier sous Windows. Le dossier data situé dans le dossier du projet ne s'était pas créé (par contre je n'ai pas compris pourquoi avac l'impossibilité de s'initialiser correctement, le conteneur a continué à fonctionner).

On a commenté les lignes "volumes" du service mysql puis recréer le conteneur (docker-compose down et docker-compose up) et là ça a marché.

Le script d'install est en train de tourner. Si c'est ok pour toi Mouna, tu peux fermer l'issue.

**Comment by mouna16** [comment]
c'est ok pour moi.
J'ai pu accéder au site

Merci Florent pour ton aide
