### ISSUE TITLE
Page Camp passé - Supprimer les références aux contenus société pour utiliser des références aux utilisateurs (organismes)

### ISSUE THREAD

**Issue by asplamagnifique** [Drupal-FR/site-drupalfr#46]
Dans le type de contenu camp : 
- les sponsors sont des USERS
- ces USERS seront des adhérents (ou non) organisme
- on utilisera un champ user reference

Sur la page du camp, on aura une vue qui listera les USER et non des contenus.

**Comment by FlorentTorregrosa** [comment]
#71 créée.

Par contre en amélioration, le fait de cibler uniquement des organismes sera à voir dans #57, car pour l'instant je ne sais pas s'il vaut mieux partir sur un rôle pour distinguer les utilisateurs organismes des autres ou s'il vaut mieux partir sur un champ booléen.

Sur la page du camp, ce n'est pas une vue mais le rendu natif du champ qui affiche les entitées référencées en mode teaser.
