### ISSUE TITLE
Mettre à jour la préprod

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#47]

**Comment by FlorentTorregrosa** [comment]
Site de préprod réinstallé.

Mais, plusieurs warning :
* il faudrait passer à PHP 7 (5.6 actuellement)
* pas de solr installé
* pas de redis installé
* pas de Varnish paramétré : varnish purge fait des warnings

**Comment by FlorentTorregrosa** [comment]
Voir avec @morvans si on peut mettre du Docker sur la préprod.

Voir Apache proxy pass suggéré par Inès.

**Comment by wallon-ines** [comment]
Voici un exemple
```
<VirtualHost 91.121.58.234:443>
        ServerName drupal8.h337pre.drupalfr.org
        ProxyPass /error/ !
        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:8100/
        ErrorLog  /var/log/httpd/drupal8_fr_error.log
        CustomLog /var/log/httpd/drupal8_fr_log common
        LogLevel info
</VirtualHost>
```


Coté settings.php pour que d8 prenne en compte le ssl (car entre Apache et le container docker c'est du http)

```
$settings['reverse_proxy'] = TRUE;
$settings['reverse_proxy_proto_header'] = 'X_FORWARDED_PROTO';
$settings['reverse_proxy_host_header'] = 'X_FORWARDED_HOST';
$settings['reverse_proxy_port_header'] = '443';
$settings['reverse_proxy_forwarded_header'] = 'FORWARDED';
```

**Comment by FlorentTorregrosa** [comment]
PHP passé de 5.6 à 7.1 sur la preprod.

J'ai commencé à suivre https://angristan.fr/installer-php-7-debian-8-jessie-depot-dotdeb, sauf que dotdeb ne va pas plus loin que 7.0 (https://www.dotdeb.org/2017/01/27/php-7-1-dotdeb/) donc j'ai suivi https://www.noobunbox.net/serveur/auto-hebergement/installer-php-7-1-sous-debian-et-ubuntu/.

J'ai pu mettre à jour le site D8 par rapport aux derniers commits de la branche 8.x-1.x.

J'ai tenté de mettre un Redis (version 2.8 fournie par Debian 8...), mais il manque la librairie PHPRedis.

J'ai pas tenté de mettre de Solr, ni de Varnish.

Au moins les personnes sans environnement de dev peuvent tester.

**Comment by FlorentTorregrosa** [comment]
Je vais essayé d'installer solr. J'ai vu qu'il y avait un solr déjà installé auparavant. Je vais essayer de me caler dessus.

**Comment by wallon-ines** [comment]
on essaye docker sur la preprod du coup ?

**Comment by FlorentTorregrosa** [comment]
Il faut se synchroniser avec @morvans avant.

À part me connecter à la preprod et à la prod, j'ai pas trop de connaissance sur comment s'est fait niveau virtualisation.

**Comment by wallon-ines** [comment]
Effectivement docker ne se lance pas de base sur un container LXC (celui que nous avons sur la préprod)
Je viens de tester sur un containter perso

```
root@www-test:~# docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
9bb5a5d4561a: Extracting [==================================================>]     985B/985B
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: permission denied
```
j'ai du modifier le fichier de conf de mon containter LXC de test
en rajoutant 
```lxc.aa_profile: unconfined```

et ça fonctionne

![capture d ecran_2018-05-07_14-45-39](https://user-images.githubusercontent.com/11542186/39702496-544470b0-5205-11e8-8f51-1a266795a63b.png)

**Comment by wallon-ines** [comment]
On va passer sur un autre hébergeur, je ferme ce ticket
