### ISSUE TITLE
[Theming] Revoir la palette de couleur

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#59]
Suite à #39

Je me suis rendu compte que par exemple sur la page charte graphique de la maquette, 3ème couleur en partant du haut à gauche ne correspondait pas à ce qu'il y avait d'écrit sur cette couleur (#e3e3d8 écrit, alors qu'en inspectant avec un color picker, c'est indiqué #cccccc).

En allant sur la maquette homepage, bloc "documentation", aucune couleur correspond au fond.

**Comment by asplamagnifique** [comment]
Si changement il y a, pouvez-vous reporter sur : https://github.com/Drupal-FR/site-drupalfr/wiki/Structure-du-site-et-navigation#codes-couleur- ?

**Comment by FlorisMoriceau** [comment]
Palette OK dans `_settings.scss`.
