### ISSUE TITLE
Installation projet

### ISSUE THREAD

**Issue by creatile** [Drupal-FR/site-drupalfr#62]
J'ai installé le projet mais j'ai eu quelques  messages d'erreur à la fin :

[error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [error]  Recursive rendering detected when rendering entity media: 1, using the field_media field on the title_text_media bundle. Aborting rendering. 
 [notice] Cron run completed.

**Comment by FlorentTorregrosa** [comment]
OK. Il y a l'issue #30 et dans le wiki https://github.com/Drupal-FR/site-drupalfr/wiki/installation, c'est indiqué "Erreurs d'indexation des paragraphes dans Search API".

Donc c'est connu et documenté. Bien qu'il faudra résoudre ce souci un jour.

Si ma réponse suffit, tu peux fermer l'issue.
