### ISSUE TITLE
Intégration - HP - Bloc Actualité

### ISSUE THREAD

**Issue by asplamagnifique** [Drupal-FR/site-drupalfr#65]
Réaliser l'intégration du bloc actu de la HP.
Reprendre les maquettes du bloc Planète (https://github.com/Drupal-FR/site-drupalfr/wiki/Page-d%27accueil#bloc-3--documentation-d8-en-fr) 
![bloc5](https://user-images.githubusercontent.com/2337791/37735589-c939c798-2d4e-11e8-873f-baeb30b8491e.png)

**Comment by FlorentTorregrosa** [comment]
De mémoire, je l'avais fait. Dans le drupal_france.theme drupal_france_preprocess_node()
Ça prend l'image du flux admin/structure/feeds/manage/planet_feed_rss/fields.
Car dans les flux RSS, le micro data image n'est pas dans les flux rss généré par Drupal.
