### ISSUE TITLE
Installation projet : erreur avec docker-compose up

### ISSUE THREAD

**Issue by Outim** [Drupal-FR/site-drupalfr#66]
La commande `docker-compose` up donne : 

```
docker-compose up
Creating sitedrupalfr_solr-showcase_1 ... done
Creating sitedrupalfr_mysql_1         ... done
Creating sitedrupalfr_mail_1          ... done
Creating sitedrupalfr_mail_1          ... 
Creating sitedrupalfr_web_1           ... error
Creating sitedrupalfr_solr_1          ... done
Creating sitedrupalfr_web_1           ... 

ERROR: for sitedrupalfr_web_1  Cannot start service web: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"mkdir /var/www/html: file exists\"": unknown

ERROR: for web  Cannot start service web: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"mkdir /var/www/html: file exists\"": unknown
ERROR: Encountered errors while bringing up the project.
```

Je ne trouve pas si l'erreur vient de mon paramétrage local ou d'ailleurs.

J'ai le docker installé par Docker Toolbox (https://docs.docker.com/toolbox/overview). `docker-compose pull` fonctionne normalement.

**Comment by FlorentTorregrosa** [comment]
On a essayé de voir ensemble, mais je n'ai pas assez d'expérience pour débloquer sous Mac (dont un Mac assez âgé pour être juste avant une stabilisation de l'intégration Docker sous Mac).

Si quelqu'un d'autre peut aider Outi.

Merci.

**Comment by Outim** [comment]
Pour info, je n'ai toujours pas trouvé :(. J'ai cherché avec "docker compose up Cannot start service web: OCI runtime create failed: container_linux.go:348" mais je ne trouve pas des cas suffisamment similaires pour que je sache m'en servir.

**Comment by morvans** [comment]
Il y a un souci avec le dossier /var/www/html qui n'existe peut-être pas. Du coup apache ne démarre pas.
Il faudrait tenter un ``docker-compose pull`` pour être sûr d'être sur les dernières images.

@FlorentTorregrosa, où sont les sources des images utilisées dans notre docker-compose.yml ?

**Comment by Outim** [comment]
En fait mon /var est un symlink (?) vers /private/var, et là en effet le répertoire www n'existe pas. Je l'avais créé pour voir mais ça n'a rien changé. Je ne sais pas vraiment quoi chercher à modifier pour que ça y arrive. J'ai fait `docker-compose pull` avant chaque tentative.

**Comment by FlorentTorregrosa** [comment]
@morvans : https://github.com/FlorentTorregrosa/docker-drupal-project/tree/8.x/docker-images

php-apache : https://github.com/FlorentTorregrosa/docker-drupal-project/tree/8.x/docker-images/php-apache
php-apache-dev (celle utilisée et qui hérite de la précédente) : https://github.com/FlorentTorregrosa/docker-drupal-project/tree/8.x/docker-images/php-apache-dev

Oui, le /var/www/html est supprimé et remplacé par un lien symbolique vers /project/www qui n'existera qu'avec le montage de volume sur la machine hôte.

**Comment by FlorentTorregrosa** [comment]
@Outim la dernière fois qu'on avait regardé ensemble, pour installer le site en local, il te manquait l'équivalent de `apt-get install ca-certificates` mais pour MacOS.

As-tu pu trouver une solution ?

**Comment by wallon-ines** [comment]
@Florent Si tu supprimes le lien symbolique /var/www/html et que tu changes le WORKDIR dans ton dockerfile? ça peut pas fonctionner ?

**Comment by florent-jousseaume** [comment]
Hello,

Je mets ma contribution, comme j'ai regardé sur le poste de Mouna. Ce qui
est étonnant c'est que ça plante sur la création d'un dossier via la
commande MKDIR... mais il n'y a pas de mkdir dans les script Dockerfile de
Florent (pas moi)...

Florent,

2018-05-31 8:35 GMT+02:00 wallon-ines <notifications@github.com>:

**Comment by wallon-ines** [comment]
je suis en train de tester sans le ln pour voir https://github.com/wallon-ines/drupal-php-apache-dev/blob/dev/Dockerfile

**Comment by wallon-ines** [comment]
ça a l'aire de tourner sans le ln. reste plus qu'a tester sur une machine window$

**Comment by florent-jousseaume** [comment]
Ok, je verrais avec Mouna si ça fonctionne. Les modifications à apporter
pour tester ?

**Comment by florent-jousseaume** [comment]
Ok, mais ça c'est quand tu peux lancer le conteneur Ines :) Le conteneur
est en erreur, et pas moyen de le lancer. Je ne peux pas faire d'actions
dessus...

2018-05-31 10:26 GMT+02:00 wallon-ines <notifications@github.com>:

**Comment by wallon-ines** [comment]
la modif est a faire dans le dockerfile. c'est @FlorentTorregrosa qui a la main dessus

**Comment by FlorentTorregrosa** [comment]
Merci d'avoir regardé.

Dans https://github.com/FlorentTorregrosa/docker-drupal-project/blob/8.x/docker-images/php-apache-dev/Dockerfile, je vais laisser le /var/www:html et juste faire un `WORKDIR /project`

Le disable du vhost par défaut est déjà fait dans l'image parente.

On a testé avec @mouna16, déjà son conteneur web ne s'arrêtait plus.

Mais il n'y avait aucun volume à l'intérieur sauf ceux que Docker se fait dans son dossier à lui.

Et la réponse est dans le comentaire https://github.com/docker/compose/issues/4303#issuecomment-379563170

Docker n'arrivait plus à monter les volumes sur son PC car elle a changé de mot de passe. Merci Windows.

Je vais mettre à jour mes images par rapport à ne plus supprimer /var/www/html, peut être que ça débloquera aussi @Outim.

**Comment by FlorentTorregrosa** [comment]
Reconstruire les images en local, ça va, mais j'ai quasiment pas de débit en upload donc je les pusherai sur le hub.docker demain soir ou ce weekend.

**Comment by wallon-ines** [comment]
Le hub peut compiler à ta place

**Comment by FlorentTorregrosa** [comment]
Ça y est. C'est pushé.

Merci pour la suggestion @wallon-ines, je crois que quand je me suis créé un compte Docker c'était payant ou j'étais trop débutant pour trop comprendre comment ça marchait.

Mais je crois que je vais le mettre en place. Tu as raison.

En voyant l'interface pour paramétrer les build automatique, je comprends mieux pourquoi les gens font des dépôts git dédiés à chaque image. Je regarderai une autre fois. J'espère que je vais pas devoir séparer les Dockerfile de mon dépôt projet Drupal.

Je ferme l'issue. Si des personnes ont d'autres soucis elles pourront réouvrir ou ouvrir une nouvelle issue.

**Comment by florent-jousseaume** [comment]
Merci Florent ! Je vais essayer de trouver du temps pour réinstaller un
windows sur une machine de la maison et essayer ton image...

Le 2 juin 2018 à 12:58, Florent Torregrosa <notifications@github.com> a
écrit :

**Comment by wallon-ines** [comment]
@FlorentTorregrosa tu peux spécifier un dossier dans ton dépot
https://docs.docker.com/docker-hub/builds/#create-an-automated-build

**Comment by FlorentTorregrosa** [comment]
Oui, et c'est pas mal.

Je suis en train de réorganiser mes images Docker pour les rendre toutes avec build automatisé et avec des tags qui veulent dire quelque chose (pas comme le tag php7 alors que l'image est en PHP 7.1).

Une fois fini et ok, je vais faire une MR pour mettre à jour le docker-compose-common.yml de drupalfr et de socle drupalcampfr.

Plus faire un article sur mon site.

**Comment by FlorentTorregrosa** [comment]
L'article https://assos.centrale-marseille.fr/ftorregrosa/blog/r%C3%A9organisation-de-mes-images-docker-et-mise-en-place-builds-automatis%C3%A9s

**Comment by MistaIA** [comment]
La commande `docker-compose up` me renvoit des erreurs KeyError, suivant l'issue ci-dessous,
SVP, qu'y a t'il lieu de faire pour que `docker-compose up` s'exécute ?

https://github.com/docker/compose/issues/9397
