### ISSUE TITLE
Erreur lors du lancement de drush

### ISSUE THREAD

**Issue by wallon-ines** [Drupal-FR/site-drupalfr#68]
Lorsque je lance une commande drush, j'ai cette erreur

>   [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                           
  The service "drupalfr_meetup.meetup_helper" has a dependency on a non-existent service "messenger". 

c'est normal ?

**Comment by FlorentTorregrosa** [comment]
Vidage de cache ? :)

**Comment by wallon-ines** [comment]
non, un composer install qui n'était pas passé,  à cause du changement de version de eu_cookie_compliance que j'avais passé en beta12
