### ISSUE TITLE
Docker : Traefik + Xdebug + Phpstorm

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#73]
Je viens de remarquer qu'avec la dernière version de Phpstorm, je n'arrive plus à avoir les breakpoint Xdebug. Pourtant cela fonctionnait avec Traefik (à moins d'avoir rêvé).

Je n'ai pas changé ma conf Traefik, PHP ou PHPStorm et là je constate que ça ne marche plus.

J'ai testé avec le socle drupalcamp qui ne passe pas encore par Traefik, mais pas un mapping de port, là j'ai bien le point d'arrêt qui se fait détecter.

**Comment by pounard** [comment]
Je connais pas la VM du projet, par contre je sais qu'XDebug avec PHPStorm est super capricieux sur les mappings de chemin de fichier: si le /srv/http de ta VM est différent de ton /home/terragossa/developement/mon-project une fois sur deux il va se vautrer grave et pas réussir à faire le mapping des breakpoints. @SebCorbin avait eu des surprises avec ça.

De plus, si ton docker ne se déploie pas avec la même IP (enfin surtout si mapping de l'IP de ton host change) XDebug va pas pouvoir se connecter, vérifie donc la conf remote_host: ```xdebug.remote_host = 10.1.3.1```

T'as activé le logging de XDebug côté serveur ? ```xdebug.remote_log = /tmp/xdebug.log``` ça permet déjà de voir s'il a réussi à se connecter à ton host ou pas.

**Comment by FlorentTorregrosa** [comment]
Merci @pounard pour ton aide.

Ton xdebug.remote_host m'a mis sur une voie. En faisant des `docker network inspect`, j'ai voulu voir le network host, j'ai vu que Traefik n'avait pas d'IP.

```bash
~/sites/docker-drupal-project-d8$ docker network inspect host 
[
    {
        "Name": "host",
        "Id": "c12fb38c0d04ed4e7011c1616ddea78b84d3952faa4b6cc674802eda8ae4645d",
        "Created": "2017-03-05T16:39:33.232580695+01:00",
        "Scope": "local",
        "Driver": "host",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "490a3cb6c9b96942db34823e2c6c8e7b10389e6ca1938275ba6b2d7286cfbdcb": {
                "Name": "traefik_traefik_1",
                "EndpointID": "db9c0bb387c8ec12c0319d524ecf8870fc16683a0988a887345e50feae668d56",
                "MacAddress": "",
                "IPv4Address": "",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]

```

J'ai donc trouvé le commit "responsable" : https://github.com/FlorentTorregrosa/docker-drupal-project/commit/01bc7251d8837cef147fce2f086d1adfee56778e#diff-44367f92eae127d5c6c8173cb5f2d471R11

Avant ce commit, pas de souci, PhpStorm (donc même la dernière version, je viens de tester) arrive à se débrouiller pour son mapping de chemin de fichier.

À partir de ce commit, boom, il y arrive plus.

Je vais voir si j'arrive à fixer en lui indiquant l'IP du remote host ou si @morvans a une suggestion par rapport au `network_mode: host` qui simplifie la conf Docker/Traefik.

**Comment by morvans** [comment]
On 03/04/2018 20:21, Florent Torregrosa wrote:
> Avant de continuer à chercher, je vais attendre l'avis de @morvans
> <https://github.com/morvans>.

Genre... 

Pour Xdebug, c'est le container dans lequel tourne PHP qui va tenter de
se connecter à phpStorm.

Comme phpStorm est généralement accessible sur la même IP que celle
qu'utilise le navigateur comme IP source pour joindre traefik, on peut
utiliser la directive xdebug.remote_connect_back qui permet de dire à
Xdebug de se connecter dynamiquement à l'IP d'où vient la requête. Sur
mes environnements, j'utilise cette config xdebug (voir [1]).

Le trick, si traefik est en network_mode: host, c'est de **NE PAS
utiliser 127.0.0.1** pour s'y connecter, mais plutôt l'IP que docker
assigne à docker0, par exemple. Sinon, l'IP source de la connexion HTTP
sera 127.0.0.1 et pour le container PHP elle n'a pas la même
signification, et donc la connexion n'arrive jamais jusqu'à phpStorm.

Par exmple, le wildcard *.docker, chez moi, pointe sur 172.17.0.1.

Sans network_mode: host, comme on s'adresse à traefik via une IP qui
n'est pas 127.0.0.1, forcément, on ne tombe pas dans ce piège, par
contre il faut impérativement assigner une IP stable à traefik pour que
le wildcard éventuel soit stable.

Ce setup est utilisé chez nous avec comme lune/dev-drupal [2] comme
image de base et ça roule sans accroc.

Si c'est pas clair, je précise, n'hésitez pas.

[1]
https://github.com/icilalune/moon-docker-dev-drupal/blob/master/xdebug.ini
[2] https://hub.docker.com/r/lune/dev-drupal/



-- Simon

**Comment by FlorentTorregrosa** [comment]
Merci Simon pour ton retour.

J'ai tenté les manips suivantes :
* Changer mon wilcard *.docker.localhost de 127.0.0.1 vers 172.17.0.1 (IP du docker0 / bridge), restart des services dnsmasq et networkmanager. si je ping web.ddp8.docker.localhost, il va bien taper dans 172.17.0.1
* ma conf xdebug :
```ìni
xdebug.max_nesting_level = 500
xdebug.remote_autostart = On
xdebug.remote_connect_back = On
xdebug.remote_enable = On
xdebug.remote_port = 9000
xdebug.remote_log = /tmp/xdebug.log
xdebug.idekey = PHPSTORM
```
* conf Traefik et Docker-compose inchangées de ce qui est versionné dans https://github.com/Drupal-FR/site-drupalfr ou dans https://github.com/FlorentTorregrosa/docker-drupal-project

Breakpoint dans index.php, pas pris en compte.

J'ai mis un var_dump($_SERVER); die(); dans le index.php pour voir un peu tous les headers qu'il voit :
```
/project/www/index.php:14:
array (size=42)
  'protossl' => string '' (length=0)
  'HTTP_AUTHORIZATION' => string '' (length=0)
  'HTTP_HOST' => string 'web.ddp8.docker.localhost' (length=25)
  'HTTP_USER_AGENT' => string 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36' (length=104)
  'HTTP_ACCEPT' => string 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' (length=74)
  'HTTP_ACCEPT_ENCODING' => string 'gzip, deflate, sdch, br' (length=23)
  'HTTP_ACCEPT_LANGUAGE' => string 'fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4' (length=35)
  'HTTP_CACHE_CONTROL' => string 'max-age=0' (length=9)
  'HTTP_COOKIE' => string 'SESS4efa770624e8b59162853da9baccd9cf=5ccp9gS9gtstb7bRIgnioy2c-NGyA3bk0AlGr5Bs5R8' (length=80)
  'HTTP_DNT' => string '1' (length=1)
  'HTTP_UPGRADE_INSECURE_REQUESTS' => string '1' (length=1)
  'HTTP_X_FORWARDED_FOR' => string '::1' (length=3)
  'HTTP_X_FORWARDED_HOST' => string 'web.ddp8.docker.localhost' (length=25)
  'HTTP_X_FORWARDED_PORT' => string '80' (length=2)
  'HTTP_X_FORWARDED_PROTO' => string 'http' (length=4)
  'HTTP_X_FORWARDED_SERVER' => string 'fixe-2-florent' (length=14)
  'HTTP_X_REAL_IP' => string '::1' (length=3)
  'PATH' => string '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' (length=60)
  'SERVER_SIGNATURE' => string '<address>Apache/2.4.10 (Debian) Server at web.ddp8.docker.localhost Port 80</address>
' (length=86)
  'SERVER_SOFTWARE' => string 'Apache/2.4.10 (Debian)' (length=22)
  'SERVER_NAME' => string 'web.ddp8.docker.localhost' (length=25)
  'SERVER_ADDR' => string '172.20.0.9' (length=10)
  'SERVER_PORT' => string '80' (length=2)
  'REMOTE_ADDR' => string '172.20.0.1' (length=10)
  'DOCUMENT_ROOT' => string '/project/www' (length=12)
  'REQUEST_SCHEME' => string 'http' (length=4)
  'CONTEXT_PREFIX' => string '' (length=0)
  'CONTEXT_DOCUMENT_ROOT' => string '/project/www' (length=12)
  'SERVER_ADMIN' => string 'webmaster@localhost' (length=19)
  'SCRIPT_FILENAME' => string '/project/www/index.php' (length=22)
  'REMOTE_PORT' => string '44989' (length=5)
  'GATEWAY_INTERFACE' => string 'CGI/1.1' (length=7)
  'SERVER_PROTOCOL' => string 'HTTP/1.1' (length=8)
  'REQUEST_METHOD' => string 'GET' (length=3)
  'QUERY_STRING' => string '' (length=0)
  'REQUEST_URI' => string '/' (length=1)
  'SCRIPT_NAME' => string '/index.php' (length=10)
  'PHP_SELF' => string '/index.php' (length=10)
  'REQUEST_TIME_FLOAT' => float 1523097325.33
  'REQUEST_TIME' => int 1523097325
  'argv' => 
    array (size=0)
      empty
  'argc' => int 0
```

Dans les logs xdebug, j'obtiens toujours :
```bash
Log opened at 2018-04-07 10:35:25
I: Checking remote connect back address.
I: Checking header 'HTTP_X_FORWARDED_FOR'.
I: Remote address found, connecting to ::1:9000.
W: Creating socket for '::1:9000', connect: Network is unreachable.
E: Could not connect to client. :-(
Log closed at 2018-04-07 10:35:25
```

Je crois qu'il me manque d'assigner une IP stable à Traefik, comme indiqué dans ton commentaire.

**Comment by FlorentTorregrosa** [comment]
Je ne vois pas comment assigner une IP stable à Traefik.

Car si dans le docker-compose.yml de Traefik je mets :
```yaml
version: '2'

services:
  traefik:
    image: traefik:1.5-alpine
#    restart: always
    ports:
      - "80:80"
#      - "443:443"
      - "8080:8080"
    network_mode: host
    networks:
      bridge:
        ipv4_address: 172.17.0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.enable=true"
```

Là il me dit : 
> ERROR: 'network_mode' and 'networks' cannot be combined

**Comment by pounard** [comment]
Ah j'ai trouvé ma propre réponse sur https://xdebug.org/docs/all_settings#remote_connect_back

> If enabled, the xdebug.remote_host setting is ignored and Xdebug will try to connect to the client that made the HTTP request. It checks the $_SERVER['HTTP_X_FORWARDED_FOR'] and $_SERVER['REMOTE_ADDR'] variables to find out which IP address to use.

Je vais commencer à taner les admins qui préparent nos VM de dev pour leur dire d'essayer d'utiliser ça. À ce jour comme les configurations sont provisionnés dynamiquement dans nos VM, celle de XDebug est généré avec un remote_host qui est l'IP de la machine hôte dans un sous-réseau dédié au projet au moment du setup. C'est efficace, mais avec l'aspect dynamique ça sera même encore plus simple.

**Comment by morvans** [comment]
Logiquement traefik ajoute un header X-Forwarded-For afin que le serveur web derrière connaisse l'IP réelle du client.

Le 7 avril 2018 14:23:49 GMT+02:00, Pierre <notifications@github.com> a écrit :
>> Comme phpStorm est généralement accessible sur la même IP que celle
>qu'utilise le navigateur comme IP source pour joindre traefik, on peut
>utiliser la directive xdebug.remote_connect_back qui permet de dire à
>Xdebug de se connecter dynamiquement à l'IP d'où vient la requête
>
>Merci énormément pour ça, je ne connaissais pas cette méthode ! Ça se
>comporte comment avec des reverse proxy en front ? On peut lui donner,
>par exemple, un header HTTP qui contient la vraie adresse ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Drupal-FR/site-drupalfr/issues/73#issuecomment-379465579

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by pounard** [comment]
> Logiquement traefik ajoute un header X-Forwarded-For afin que le serveur web derrière connaisse l'IP réelle du client.

Tu devrais vérifier qu'il est bien configuré alors.

**Comment by morvans** [comment]
@florent
C'est normal. network_mode: host fait que le container partage la stack réseau avec l'host, comme un processus "normal".

De toute façon, l'IP de traefik on s'en fiche, ce qu'il faut c'est que le container web (xdebug) se connecte à l'IP sur laquelle écoute phpStorm.

Le 7 avril 2018 12:58:28 GMT+02:00, Florent Torregrosa <notifications@github.com> a écrit :
>Je ne vois pas comment assigner une IP stable à Traefik.
>
>Car si dans le docker-compose.yml de Traefik je mets :
>```yaml
>version: '2'
>
>services:
>  traefik:
>    image: traefik:1.5-alpine
>#    restart: always
>    ports:
>      - "80:80"
>#      - "443:443"
>      - "8080:8080"
>    network_mode: host
>    networks:
>      bridge:
>        ipv4_address: 172.17.0.2
>    volumes:
>      - /var/run/docker.sock:/var/run/docker.sock
>      - ./traefik.toml:/etc/traefik/traefik.toml
>    labels:
>      - "traefik.enable=true"
>```
>
>Là il me dit : 
>> ERROR: 'network_mode' and 'networks' cannot be combined
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Drupal-FR/site-drupalfr/issues/73#issuecomment-379461123

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by morvans** [comment]
Je devrais, oui. Dès que je suis devant un vrai ordinateur.

Le 7 avril 2018 14:32:17 GMT+02:00, Pierre <notifications@github.com> a écrit :
>> Logiquement traefik ajoute un header X-Forwarded-For afin que le
>serveur web derrière connaisse l'IP réelle du client.
>
>Tu devrais vérifier qu'il est bien configuré alors.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Drupal-FR/site-drupalfr/issues/73#issuecomment-379466062

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by FlorentTorregrosa** [comment]
J'ai repris calmement les différents échanges et suis arrivé à un résultat qui marche avec le network_mode: host.

Dans le php.ini, j'ai commenté `xdebug.remote_connect_back` car ça annule le `xdebug.remote_host` (comme indiqué par @pounard) et mis `xdebug.remote_host = 172.17.0.1`

Là ça marche avec le reste de la conf actuellement versionnée.

J'ai tenté de faire ajouter par Traefik le X-Forwarded-For à 172.17.0.1 avec `- "traefik.frontend.headers.customRequestHeaders=X-FORWARDED-FOR:172.17.0.1"`, mais il ajoutait ça au header qu'il mettait lui et je me retrouvais avec un header valant `172.17.0.1, ::1` et ça ne marchait pas.

On part sur ça ? Je commit ce changement dans le php.ini versionné ?

Note : @morvans, mon pseudo n'est pas "florent", mais @florenttorregrosa ;),

**Comment by morvans** [comment]
On 08/04/2018 21:43, Florent Torregrosa wrote:
>
> J'ai repris calmement les différents échanges et suis arrivé à un
> résultat qui marche avec le network_mode: host.
>
> Dans le php.ini, j'ai commenté |xdebug.remote_connect_back| car ça
> annule le |xdebug.remote_host| (comme indiqué par @pounard
> <https://github.com/pounard>) et mis |xdebug.remote_host = 172.17.0.1|
>
> Là ça marche avec le reste de la conf actuellement versionnée.
>
> J'ai tenté de faire ajouter par Traefik le X-Forwarded-For à
> 172.17.0.1 avec |-
> "traefik.frontend.headers.customRequestHeaders=X-FORWARDED-FOR:172.17.0.1"|,
> mais il ajoutait ça au header qu'il mettait lui et je me retrouvais
> avec un header valant |172.17.0.1, ::1| et ça ne marchait pas.
>
> On part sur ça ? Je commit ce changement dans le php.ini versionné ?
>
On a pas d'assurance que tous les docker0 du monde valent 172.17.0.1.

On peut le commiter tel quel si ca permet d'avancer mais je vais bien
finir pas trouver pourquoi ca marche dans mes environnements habituels
et pas là.

> Note : @morvans <https://github.com/morvans>, mon pseudo n'est pas
> "florent", mais @FlorentTorregrosa
> <https://github.com/FlorentTorregrosa> ;),
>
Noté :)

**Comment by FlorentTorregrosa** [comment]
OK.

Oui, le 172.17.0.1 hardcodé dans la conf ne me plaît pas non plus.

Je te laisse chercher, au moins il y a une solution de repli.

Xdebug c'est plutôt pour les dév back et là en ce moment le gros du travail c'est le theming donc ça peut attendre.

**Comment by FlorentTorregrosa** [comment]
Pour essayer de faire avancer (et terminer ?) le sujet, je suis tombé sur https://serversforhackers.com/s/xdebug-in-docker, dont le résultat est dans un gist https://gist.github.com/fideloper/d3d0d0add6d37bec050a8277e51da459.

Avec une utilisation du fichier .env plutôt que du export comme dans ce que j'ai trouvé.

Comme ça ça permettrait de résoudre le problème de l'adresse ip et de permettre de désactiver ou activer xdebug lors du démarrage du conteneur.

Qu'en pensez-vous ?

**Comment by morvans** [comment]
Le principe est pas mal.

Par contre, ca serait peut etre mieux de l'implémenter le cas par défaut
à l'envers (xdebug désactivé par défaut si la variable n'est pas
présente ou à une valeur qui n'est pas gérée).

Et autant utiliser une variable "ENABLE_XDEBUG" c'est plus clair pour
tout le monde.

Dans le script, tu prévois que c'est false par défaut, comme ça si on ne
la configure pas (= si on a pas de .env, ou qu'il n'est pas à jour),
c'est off.

(je n'ai pas vérifié le repo récemment, mais on est bien d'accord qu'on
gitignore le .env ?)

A+

**Comment by FlorentTorregrosa** [comment]
Merci @morvans pour ton retour.

Oui, désactivé par défaut, c'est mieux.

Le .env n'est pas versionné, il y a le example.env qui lui l'est.

**Comment by FlorentTorregrosa** [comment]
Et voilà https://github.com/FlorentTorregrosa/docker-drupal-project/commit/a31a1f3db2060136bbac9c1898d3d7bacc4bba29 !

Il me reste à récupérer dynamiquement l'IP du bridge pour la mettre dans le .env. Mais la commande peut varier d'une distrib à l'autre, donc je ne sais pas si cela va être possible.

**Comment by FlorentTorregrosa** [comment]
J'ai fait un test pour voir s'il y a une différence de performance.

un `time ./scripts/install.sh`

Avec Xdebug : 4 minutes
Sans Xdebug : 3 minutes

Après peut être que sur Mac @FlorisMoriceau verra plus la différence.

**Comment by FlorentTorregrosa** [comment]
Bon pour le côté détecter dynamiquement l'IP de la passerelle du docker0 je passe.

@morvans, si le commit est ok pour toi, je l'applique sur site-drupalfr et socle-drupalcampfr.

**Comment by FlorentTorregrosa** [comment]
Le seul point "négatif", c'est que si on change la valeur d'une variable d'environnement ça recrée le conteneur du coup plus d'historique de commande dans le conteneur.

Faudra que je regarde pour mettre en place un système comme dans https://medium.com/ma-digital-services/dev-env-5d35b97f3473 (ahoy ou makefile).

**Comment by wallon-ines** [comment]
plus utile
