### ISSUE TITLE
Incohérence versions Docker

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#75]
Je viens de rebaser ma branche `feature/16_main-menu` sur 8x, 
Et comme les fois dernières, je ne peux faire un `docker-compose up` sans modifier le ficher `docker-compose-common.yml`

Cette erreur apparaît : 
```
$ docker-compose up
ERROR: Version mismatch: file ./docker-compose.yml specifies version 2.0 but extension file /home/floris/Projects/drupal.fr/docker-compose-common.yml uses version 2.3
```

**Comment by FlorentTorregrosa** [comment]
Salut Floris,

Ce n'est pas le docker-compose-common qu'il faut changer, mais ton docker-compose.yml, compares le avec le example.docker-compose.yml, pour voir les différences.

De plus, si ton exécutable docker-compose a été téléchargé il y a longtemps, il se peut qu'il ne supporte pas les fichiers en version 2.3 et dans ce cas, il faut réinstaller la dernière version de docker-compose par dessus.

**Comment by FlorisMoriceau** [comment]
Mon docker-compose était effectivement out of date.

Désolé. :'(
