### ISSUE TITLE
Intégration HP Rencontre / Meetups

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#82]
Intégration du bloc comme défini dans les [specs](https://github.com/Drupal-FR/site-drupalfr/wiki/Page-d%27accueil#bloc-4--rencontrez-%C3%A9changez-meetups).

**Comment by FlorentTorregrosa** [comment]
Mail envoyé :)

**Comment by FlorisMoriceau** [comment]
Super ! Merci !

**Comment by FlorentTorregrosa** [comment]
On peut supprimer la branche 82_HP_meetups ?

**Comment by FlorisMoriceau** [comment]
Sure!
