### ISSUE TITLE
Vulnérabilité package npm

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#87]
J'ai reçu 2 alertes de Github à cause d'une extension hoek vue dans le package-lock.json des thèmes drupal_france et drupalfr_theme.

La version 4.2.0 lui plaît pas, il veut qu'on mette a minima la 5.0.3.

J'ai voulu faire un npm update et là il me met la version 2.16.3.

Du coup @FlorisMoriceau, il y a moyen de mettre à jour ou on peut dire à Github d'ignorer.

**Comment by FlorisMoriceau** [comment]
Bon, je viens de mettre les mains dans le cambouis.
C'est assez bizarre en effet que ce soit la version 2.16.3 qui soit marquée en dépendance, mais aussi que GitHub veuille la version 5.0.3 à minima, puisque selon [la page du module](https://www.npmjs.com/package/hoek), la version de sécurité est la 4.2.1

On a 3 modules qui appellent par dépendance ce paquet à sa version 2.x.x. `boom`, `hawk` et `request`.

Il y a tellement de dépendances que je n'arrive pas à savoir d'où vient réellement l'origin du problème.

**Comment by FlorisMoriceau** [comment]
Du coup, j'ai mis a jour le thème ZF (aucune modification significative nous concernant) ainsi que les packages npm appelés dans le thème `drupal_france`.

Pour le thème `drupalfr_theme`, on oublie, il a vocation à disparaître.

**Comment by FlorentTorregrosa** [comment]
Oui pour drupalfr_theme, j'ai déjà dit à Github d'ignorer.
