### ISSUE TITLE
Permissions sur le dossier /sites/default

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#9]
A chaque réinstallation, je dois, pour pouvoir pull / push faire un 
`chmod 755 www/sites/default`

Est-ce que la modification d'un des scripts d'install permettrait de corriger ça ?

**Comment by FlorentTorregrosa** [comment]
C'est la commande drush site-install qui modifie les permissions.

Oui tu peux modifier le script install.sh si tu veux.

Je comptais refaire une passe sur les permissions lors de la mise en ligne.
