### ISSUE TITLE
[Contrib] Feeds : Failed importing 10 Article du planètes.

### ISSUE THREAD

**Issue by wallon-ines** [Drupal-FR/site-drupalfr#92]
Il y a une erreur lors d'un drush cron

```
root@f22085ef745a:/project/www# drush cron
 [notice] Release (drupal 8.2.6) was imported/updated
 [notice] Release (drupal 8.2.5) was imported/updated
 [notice] Release (drupal 8.2.4) was imported/updated
 [notice] Release (drupal 8.2.3) was imported/updated
 [notice] Release (drupal 8.2.2) was imported/updated
 [notice] Release (drupal 8.2.1) was imported/updated
 [notice] Release (drupal 8.2.0) was imported/updated
 [notice] Release (drupal 8.2.0-rc2) was imported/updated
 [notice] Release (drupal 8.2.0-rc1) was imported/updated
 [notice] Release (drupal 8.2.0-beta3) was imported/updated
 [notice] Cron run completed.
 [error]  Message: Failed importing 10 Article du planètes.
 
 [warning] Message: Render context is empty, because render() was called outside of a 
renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or 
#lazy_builder/#pre_render instead.
```

c'est normal ?

**Comment by FlorentTorregrosa** [comment]
Non c'est pas normal. Ça vient du module feeds (je pense).

**Comment by wallon-ines** [comment]
Étrange. Après un drush -d cron plus de message d'erreur.

**Comment by FlorentTorregrosa** [comment]
@wallon-ines j'ai trouvé.

J'ai dû mettre des var_dump car le message d'erreur ne pouvait pas être rendu via Drush. Je vais ouvrir une issue sur feeds pour ça.

Mais en remontant les var_dump, feeds avait un problème avec le format inséré dans le body, parce que basic_html n'est pas autorisé pour les anonymes et donc en lançant l'import via Drush, l'utilisateur utilisé est l'utilisateur anonyme et donc il ne passe pas la validation d'entité.

Dommage, j'avais fait un patch qui a été commité pour que ce soit l'auteur du flux qui soit aussi l'auteur des entités importées, mais visiblement ça doit intervenir à un autre moment dans l'import et donc ça passe pas.

J'ai fait la PR #105.

Je te laisse tester la PR et fermer l'issue.

Et oui, la fréquence d'import des flux est réglé sur 1 heure, tu peux modifier ça dans admin/structure/feeds/manage/planet_feed_rss?destination=/admin/structure/feeds.

D'où le fait qu'au second drush cron, ça bugué plus car le flux n'était alors plus importé.

**Comment by FlorentTorregrosa** [comment]
Visiblement l'issue à refait surface : https://www.drupal.org/project/feeds/issues/2708693

**Comment by FlorentTorregrosa** [comment]
Pour l'affichage dans Drush : https://www.drupal.org/project/feeds/issues/2969259

**Comment by wallon-ines** [comment]
plus d'erreur de mon coté

```Run CRON.
 [notice] Release (drupal 8.5.0-rc1) was imported/updated
 [notice] Release (drupal 8.5.0-beta1) was imported/updated
 [notice] Release (drupal 8.5.0-alpha1) was imported/updated
 [notice] Release (drupal 8.4.8) was imported/updated
 [notice] Release (drupal 8.4.7) was imported/updated
 [notice] Release (drupal 8.4.6) was imported/updated
 [notice] Release (drupal 8.4.5) was imported/updated
 [notice] Release (drupal 8.4.4) was imported/updated
 [notice] Release (drupal 8.4.3) was imported/updated
 [notice] Release (drupal 8.4.2) was imported/updated
 [notice] Cron run completed.
 [notice] Message: There are no new Article du planètes.```

**Comment by FlorentTorregrosa** [comment]
Ok.
