### ISSUE TITLE
[Intégration] Page Meetups 

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#97]
Deux colonnes : 
1/2 : Liste des meetups
1/2 : carte des meetups

https://projects.invisionapp.com/share/HZ9S0P5C8#/screens/211677700

**Comment by FlorentTorregrosa** [comment]
https://github.com/Drupal-FR/site-drupalfr/wiki/page-meetups

**Comment by wallon-ines** [comment]
Je viens de rajouter la classe large-6

![capture d ecran 2018-05-07 a 14 49 28-fullpage](https://user-images.githubusercontent.com/11542186/39702793-3a5dc5ba-5206-11e8-9ea2-4435b918401c.png)

par contre en mode mobile je rajouterai bien un margin-bottom: 20px;

![capture d ecran 2018-05-07 a 14 49 30-fullpage](https://user-images.githubusercontent.com/11542186/39702851-67789f84-5206-11e8-90b1-ac390a892265.png)

**Comment by FlorisMoriceau** [comment]
Alors : 
- Pour le mobile, réduire la hauteur de la map.
- Pour le mobile, ajouter un `margin-bottom : $global-margin;`
- Sur tablette et mobile : 
  - Faire en sorte que la map et la liste aient la même hauteur (en dur)
  - Fixer la hauteur de la map pour qu'elle corresponde à 6 éléments de liste (grosso modo) 
  - Ajouter un overflow à l'intérieur du wrapper de la liste.

Tu vois ce que je veux dire ?

**Comment by FlorentTorregrosa** [comment]
@FlorisMoriceau, je ne comprends pas tes demandes "sur tablettes et mobiles".

C'est pour éviter d'avoir à trop scroller pour arriver en bas de page ?

Mais il n'y a rien d'autre sur la page donc c'est pas gênant, je pense.

On peut en discuter à la prochaine réunion.
