### ISSUE TITLE
URGENT [Intégration] Layout global

### ISSUE THREAD

**Issue by FlorisMoriceau** [Drupal-FR/site-drupalfr#99]
Header + Main + Sidebar à thémer.

**Comment by FlorisMoriceau** [comment]
@FlorentTorregrosa FYI Il va falloir que je créé des nouveaux types de paragraphe pour gérer le layout.

**Comment by FlorentTorregrosa** [comment]
@FlorisMoriceau On peut se faire un hangout pour se synchoniser là-dessu stp ?

**Comment by FlorisMoriceau** [comment]
Alors, j'ai créé un type de paragraphe 3/4 1/4.
Ca ressemble à ça : 
![capture du 2018-05-03 17-59-11](https://user-images.githubusercontent.com/1312944/39588955-2f715ac4-4efd-11e8-936c-c301a5030737.png)

Du coup, plus besoin des `blocks visibility group`  sur les pages éditoriales, ni des blocs custom de titres.
Reste maintenant pour moi à gérer l'affichage des contenus automatisés, comme la page de téléchargement.

**Comment by FlorisMoriceau** [comment]
> Ça y est je me souviens pourquoi on n'était pas partie sur ça. Pour les pages de vues...
> As-tu fait un type de paragraphe "bloc" ? Si oui, on peut transformer les pages de vues en blocs et utiliser ça.

Non, pour le moment, on a un paragraphe qui a deux champs : 
- Main Area | field_main_area | Entity reference revisions 
- Right Sidebar | field_sidebar | Block (plugin)

Mais oui, c'est ce que je pensais, et je trouve l'idée séduisante. Ca nécessite cependant de reprendre toutes les pages de vues existantes, et créer de nouvelles pages éditos.  

> Et est-ce qu'on pousse plus loin ton type de paragraphe 3/4 1/4, en paragraphe 2 colonnes et comme pour le type de paragraphe "titre + texte + média" avoir un champ pour contrôler le nombre de colonne ?

Oui, on peut faire ça, et ajouter le champ `background-color` dessus.
De plus, on pourrait ajouter une checkbox "Contraste Inversé" afin d'avoir le texte en blanc automatiquement si l'option est cochée.

**Comment by FlorisMoriceau** [comment]
Voici la bayte : https://github.com/Drupal-FR/site-drupalfr/tree/feature/99_global-layout

**Comment by FlorentTorregrosa** [comment]
TODO :
* création type de paragraphe layout_onecol
* reprise des vues pages
* utilisation paragraphe (html) en remplacement des blocs de contenus des sidebars
* utilisation paragraphe bloc pour positionnement des blocs page d'accueil

**Comment by FlorentTorregrosa** [comment]
Effets de bord potentiels pensés pendant la nuit :
* devoir utiliser l'ajax sur les vues (pour la pagination et) les filtres exposés
* voir si les blocs de facets fonctionnent avec une vue bloc
* indexation search api : il y a déjà des warnings avec les paragraphes, je me demande si on va pas faire indexer le rendu

**Comment by FlorentTorregrosa** [comment]
Les blocs de facettes fonctionnent avec une vue bloc, mais seulement si le bloc est placé via "block layout". Si le bloc de vue est injecté via le champ "block field" là ça marche pas (les blocs de facettes injecté via "block field" eux fonctionnent).

Alors pour l'instant, je ne touche pas à la page des références et à la recherche.

**Comment by FlorentTorregrosa** [comment]
je suis en train de reprendre les pages une par une. J'ai pushé quelques commits en attendant histoire de pouvoir tester si tu veux @FlorisMoriceau .

**Comment by FlorentTorregrosa** [comment]
Restera :
* page forum : on ne sait pas encore à quoi ça doit ressembler
* page liste des adhérents
* page liste des offres d'emploi : sera fait lorsque le fonctionnement sera repris
* page liste des organismes : sera fait lorsque le fonctionnement sera repris
* page médiathèque : on ne sais pas encore ce qu'on veut là-dessus
* page des flux du planète : accessible depuis la page planète, à voir si à transformer en bloc à mettre dans la sidebar du planète

**Comment by FlorentTorregrosa** [comment]
En plus au passage ça a permis de repasser sur views avec de l'infinite scroll qui était cassée car l'ajax n'est plus activé automatiquement.

**Comment by FlorentTorregrosa** [comment]
@FlorisMoriceau : ok pour moi.

Par contre je n'ai toujours pas utilisé le paragraphe layout 1 colonne. J'ai dû louper un truc dans la manière dont tu imaginais la chose.

Je te laisse ajouter les champs pour gérer des background color et autres effets front.

Je vais encore un peu toucher aux blocs, si je peux encore simplifier.

**Comment by FlorisMoriceau** [comment]
La branche est mergée.

On ferme cette issue.
